VALUES_SORT_VALUES = [
"Saving money",
"Exercise",
"Being involved with community",
"Being able to keep appointments",
"Being able to use my abilities",
"Working",
"Family",
"Religion",
"Getting rich",
"Completing my education",
"Free time",
"Supporting my family financially",
"Staying healthy",
"Owning a house",
"Having a car",
"Having rewarding friendships",
"Recovery",
"Traveling",
"Having health insurance",
"Spirituality",
"Having a meaningful job",
"Dependability",
"Solitude",
"Adventure",
"Independence",
"Challenge",
"Loyalty",
"Courage",
"Trustworthy",
"Contribution",
"Stability",
"Growth",
"Helping others"
]